In [7]:
import pandas as pd
import numpy as np
from datetime import datetime as dt

In [8]:
path = "E:/FISEC-DPME/Extraction Tableau/excel/UEMOA/situation financiere_data_2019.xlsx"
df_tab = pd.read_excel(path)
df_tab.tail(5)

,Ordre Poste,POSTE,Arrete,Libelle Pays,Code Assujetti,Sigle Assujetti,Ordre Colonne,Libelle Colonne,Valeurn
84555,47,Creances en souffrance / PME-PMI,31/01/2019 00:00:00,Togo,TT0187M1,SGB - TOGO,7.0,Menages Particuliers\t,0.0
84556,47,Creances en souffrance / PME-PMI,31/10/2019 00:00:00,Togo,TT0187M1,SGB - TOGO,7.0,Menages Particuliers\t,0.0
84557,47,Creances en souffrance / PME-PMI,28/02/2019 00:00:00,Togo,TT0187M1,SGB - TOGO,7.0,Menages Particuliers\t,0.0
84558,47,Creances en souffrance / PME-PMI,31/12/2019 00:00:00,Togo,TT0187M1,SGB - TOGO,7.0,Menages Particuliers\t,0.0
84559,47,Creances en souffrance / PME-PMI,31/08/2019 00:00:00,Togo,TT0187M1,SGB - TOGO,7.0,Menages Particuliers\t,0.0

In [8]:
df_tab.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84560 entries, 0 to 84559
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Ordre Poste      84560 non-null  int64
 1   POSTE            84560 non-null  object
 2   Arrete           84560 non-null  object
 3   Libelle Pays     84560 non-null  object
 4   Code Assujetti   84560 non-null  object
 5   Sigle Assujetti  84560 non-null  object
 6   Ordre Colonne    81872 non-null  float64
 7   Libelle Colonne  81872 non-null  object
 8   Valeurn          81872 non-null  float64
dtypes: float64(2), int64(1), object(6)
memory usage: 5.8+ MB

In [18]:
df_tab['Libelle Pays'].unique()
res = df_tab.loc[df_tab['Libelle Pays'] == 'Burkina Faso']
res['Sigle Assujetti'].unique()

array(['UBA BURKINA', 'VISTA BANK BURKINA', 'BCB', 'SGBF', 'ECOBANK-BK',
       'BOA BURKINA', 'BSIC-BF (EX-BADC)', 'BABF', 'IB BANK', 'CBI-BF',
       'CBAO-BF', 'ORABANK CI SUCCURSALE BURKINA', '(BDU-BF)', 'WBI',
       'BADF - BURKINA FASO'], dtype=object)

In [9]:
df_tab["New_Arrete"] = pd.to_datetime(
    df_tab["Arrete"],
    dayfirst=True,
    errors="coerce"
)

In [10]:
df_tab.head(5)

,Ordre Poste,POSTE,Arrete,Libelle Pays,Code Assujetti,Sigle Assujetti,Ordre Colonne,Libelle Colonne,Valeurn,New_Arrete
0,1,Credits a la clientele / Credits aux PME-PMI,30/04/2019 00:00:00,Bénin,BB0058C1,ORABANK-BJ,1.0,Autres societes financieres\tSocietes d'assura...,0.0,2019-04-30
1,1,Credits a la clientele / Credits aux PME-PMI,31/03/2019 00:00:00,Bénin,BB0058C1,ORABANK-BJ,1.0,Autres societes financieres\tSocietes d'assura...,0.0,2019-03-31
2,1,Credits a la clientele / Credits aux PME-PMI,31/01/2019 00:00:00,Bénin,BB0058C1,ORABANK-BJ,1.0,Autres societes financieres\tSocietes d'assura...,0.0,2019-01-31
3,1,Credits a la clientele / Credits aux PME-PMI,30/06/2019 00:00:00,Bénin,BB0058C1,ORABANK-BJ,1.0,Autres societes financieres\tSocietes d'assura...,0.0,2019-06-30
4,1,Credits a la clientele / Credits aux PME-PMI,31/07/2019 00:00:00,Bénin,BB0058C1,ORABANK-BJ,1.0,Autres societes financieres\tSocietes d'assura...,0.0,2019-07-31

In [11]:
def filtreData(df_tab, poste = "Credits a la clientele / Credits aux PME-PMI",
    mois = 11,
    annee = 2019,
    pays = "Bénin",
    banque = "ORABANK-BJ"):
    

    # Appliquer les filtres
    resultat = df_tab.loc[
        (df_tab["POSTE"] == poste) &
        (df_tab["New_Arrete"].dt.month == mois) &
        (df_tab["New_Arrete"].dt.year == annee) &
        (df_tab["Libelle Pays"] == pays) &
        (df_tab["Sigle Assujetti"] == banque),
        "Valeurn"
    ]

    return resultat.sum()

In [16]:
filtreData(df_tab, "Credits a la clientele / Credits aux PME-PMI", 2, 2019, "Bénin", "ORABANK-BJ")

1650.0

In [ ]:
def credit_UEMOA(df_tab, poste = "Credits a la clientele / Credits aux PME-PMI", mois = 12, annee = 2019):

    rk_data = []
    all_pays   = ['Bénin',"Burkina Faso","Côte d Ivoire", "Guinée Bissau","Mali","Niger","Sénégal","Togo"]

    for i in all_pays:
        resultat = df_tab.loc[
                        (df_tab["POSTE"] == poste) &
                        (df_tab["New_Arrete"].dt.month == mois) &
                        (df_tab["New_Arrete"].dt.year == annee) &
                        (df_tab["Libelle Pays"] == i),
                        "Valeurn"
                    ]

        rk_data.append((resultat.sum()))

    return sum(rk_data)#.sort(reverse= True)

3340732.0

In [29]:
def credit_pays_split_par_mois(df_tab, pays = "Bénin", annee = 2019 ):

    rk_data = []

    all_mois   = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

    for i in all_mois:
        resultat = df_tab.loc[
                         
                        (df_tab["New_Arrete"].dt.month == i) &
                        (df_tab["New_Arrete"].dt.year == annee) &
                        (df_tab["Libelle Pays"] == pays),
                        "Valeurn"
                    ]

        rk_data.append(resultat.sum())

    return rk_data

In [30]:
credit_pays_split_par_mois(df_tab, pays = "Bénin", annee = 2019 )

[552959.0,
 588498.0,
 683132.0,
 622337.0,
 699106.0,
 778021.0,
 758544.0,
 768658.0,
 620133.0,
 822950.0,
 816173.0,
 785108.0]

In [1]:
def Rank_pays(poste = "Credits a la clientele / Credits aux PME-PMI", mois = 8, annee = 2019):
    rk_data = []
    all_pays   = ['Bénin',"Burkina Faso","Côte d Ivoire", "Guinée Bissau","Mali","Niger","Sénégal","Togo"]

    for i in all_pays:

        resultat = df_tab.loc[
                (df_tab["POSTE"] == poste) &
                (df_tab["New_Arrete"].dt.month == mois) &
                (df_tab["New_Arrete"].dt.year == annee) &
                (df_tab["Libelle Pays"] == i),
                "Valeurn"
            ]

        rk_data.append((resultat.sum(), i))

    rk_data.sort(reverse= True)
    return rk_data[0][1], rk_data[0][0]

In [ ]:
def Rk_instrument(mois = 9, annee = 2019, pays = 'Bénin', banque = "ORABANK-BJ"):
    types_credit = df_tab['POSTE'].unique()


    rk_data = []

    for i in types_credit:

        resultat = df_tab.loc[
                (df_tab["POSTE"] == i) &
                (df_tab["New_Arrete"].dt.month == mois) &
                (df_tab["New_Arrete"].dt.year == annee) &
                (df_tab["Libelle Pays"] == pays) &
                (df_tab["Sigle Assujetti"] == banque),
                "Valeurn"
            ]

        rk_data.append((resultat.sum(), i))
        rk_data.sort(reverse= True)

    return rk_data[0][1], rk_data[0][0]
        # return rk_data[0][1], rk_data[0][0]

[(8437.0, 'Credits a la clientele / Credits aux PME-PMI'),
 (4615.0, 'Credits a moyen terme / PME-PMI'),
 (2253.0, 'Creances en souffrance / PME-PMI'),
 (1372.0, 'Autres credits a court terme / PME-PMI'),
 (0.0, "Portefeuille d'effets commerciaux / PME-PMI"),
 (0.0, 'Credits a long terme / PME-PMI'),
 (0.0, 'Credit de location-financement / PME-PMI'),
 (0.0, 'Affacturage / PME-PMI')]

In [16]:
df_tab.head(5)

,Ordre Poste,POSTE,Arrete,Libelle Pays,Code Assujetti,Sigle Assujetti,Ordre Colonne,Libelle Colonne,Valeurn
Rk,,,,,,,,,
1,1,Credits a la clientele / Credits aux PME-PMI,2019-12-31,Bénin,BB0058C1,ORABANK-BJ,1,Autres societes financieres\tSocietes d'assura...,0
2,1,Credits a la clientele / Credits aux PME-PMI,2019-11-30,Bénin,BB0058C1,ORABANK-BJ,1,Autres societes financieres\tSocietes d'assura...,0
3,1,Credits a la clientele / Credits aux PME-PMI,2019-10-31,Bénin,BB0058C1,ORABANK-BJ,1,Autres societes financieres\tSocietes d'assura...,0
4,1,Credits a la clientele / Credits aux PME-PMI,2019-09-30,Bénin,BB0058C1,ORABANK-BJ,1,Autres societes financieres\tSocietes d'assura...,0
5,1,Credits a la clientele / Credits aux PME-PMI,2019-08-31,Bénin,BB0058C1,ORABANK-BJ,1,Autres societes financieres\tSocietes d'assura...,0

In [11]:
path = "C:/Users/ckoupoh/Documents/FISEC-DPME/Extraction Tableau/excel/situation financiere_data 2021.xlsx"
df_2021 = pd.read_excel(path)
df_2021

,Ordre Poste,POSTE,Arrete,Libelle Pays,Code Assujetti,Sigle Assujetti,Ordre Colonne,Libelle Colonne,Valeurn
0,1,Credits a la clientele / Credits aux PME-PMI,2021-12-31,Bénin,BB0058C1,ORABANK-BJ,1,Autres societes financieres\tSocietes d'assura...,0
1,1,Credits a la clientele / Credits aux PME-PMI,2021-11-30,Bénin,BB0058C1,ORABANK-BJ,1,Autres societes financieres\tSocietes d'assura...,0
2,1,Credits a la clientele / Credits aux PME-PMI,2021-10-31,Bénin,BB0058C1,ORABANK-BJ,1,Autres societes financieres\tSocietes d'assura...,0
3,1,Credits a la clientele / Credits aux PME-PMI,2021-09-30,Bénin,BB0058C1,ORABANK-BJ,1,Autres societes financieres\tSocietes d'assura...,0
4,1,Credits a la clientele / Credits aux PME-PMI,2021-08-31,Bénin,BB0058C1,ORABANK-BJ,1,Autres societes financieres\tSocietes d'assura...,0
...,...,...,...,...,...,...,...,...,...
56338,53,Creances en souffrance / Autres / PME-PMI,2021-05-31,Bénin,BB0212V1,CBI - BENIN,7,Menages Particuliers\t,0
56339,53,Creances en souffrance / Autres / PME-PMI,2021-04-30,Bénin,BB0212V1,CBI - BENIN,7,Menages Particuliers\t,0
56340,53,Creances en souffrance / Autres / PME-PMI,2021-03-31,Bénin,BB0212V1,CBI - BENIN,7,Menages Particuliers\t,0
56341,53,Creances en souffrance / Autres / PME-PMI,2021-02-28,Bénin,BB0212V1,CBI - BENIN,7,Menages Particuliers\t,0
56342,53,Creances en souffrance / Autres / PME-PMI,2021-01-31,Bénin,BB0212V1,CBI - BENIN,7,Menages Particuliers\t,0

In [17]:
df = df_2021
df.head(5)

,Ordre Poste,POSTE,Arrete,Libelle Pays,Code Assujetti,Sigle Assujetti,Ordre Colonne,Libelle Colonne,Valeurn
0,1,Credits a la clientele / Credits aux PME-PMI,2021-12-31,Bénin,BB0058C1,ORABANK-BJ,1,Autres societes financieres\tSocietes d'assura...,0
1,1,Credits a la clientele / Credits aux PME-PMI,2021-11-30,Bénin,BB0058C1,ORABANK-BJ,1,Autres societes financieres\tSocietes d'assura...,0
2,1,Credits a la clientele / Credits aux PME-PMI,2021-10-31,Bénin,BB0058C1,ORABANK-BJ,1,Autres societes financieres\tSocietes d'assura...,0
3,1,Credits a la clientele / Credits aux PME-PMI,2021-09-30,Bénin,BB0058C1,ORABANK-BJ,1,Autres societes financieres\tSocietes d'assura...,0
4,1,Credits a la clientele / Credits aux PME-PMI,2021-08-31,Bénin,BB0058C1,ORABANK-BJ,1,Autres societes financieres\tSocietes d'assura...,0

870

In [12]:
df_updated = pd.concat([df_FISEC, df_2021], ignore_index=True)
df_updated

,Ordre Poste,POSTE,Arrete,Libelle Pays,Code Assujetti,Sigle Assujetti,Ordre Colonne,Libelle Colonne,Valeurn
0,1,Credits a la clientele / Credits aux PME-PMI,2019-12-31,Bénin,BB0058C1,ORABANK-BJ,1,Autres societes financieres\tSocietes d'assura...,0
1,1,Credits a la clientele / Credits aux PME-PMI,2019-11-30,Bénin,BB0058C1,ORABANK-BJ,1,Autres societes financieres\tSocietes d'assura...,0
2,1,Credits a la clientele / Credits aux PME-PMI,2019-10-31,Bénin,BB0058C1,ORABANK-BJ,1,Autres societes financieres\tSocietes d'assura...,0
3,1,Credits a la clientele / Credits aux PME-PMI,2019-09-30,Bénin,BB0058C1,ORABANK-BJ,1,Autres societes financieres\tSocietes d'assura...,0
4,1,Credits a la clientele / Credits aux PME-PMI,2019-08-31,Bénin,BB0058C1,ORABANK-BJ,1,Autres societes financieres\tSocietes d'assura...,0
...,...,...,...,...,...,...,...,...,...
117560,53,Creances en souffrance / Autres / PME-PMI,2021-05-31,Bénin,BB0212V1,CBI - BENIN,7,Menages Particuliers\t,0
117561,53,Creances en souffrance / Autres / PME-PMI,2021-04-30,Bénin,BB0212V1,CBI - BENIN,7,Menages Particuliers\t,0
117562,53,Creances en souffrance / Autres / PME-PMI,2021-03-31,Bénin,BB0212V1,CBI - BENIN,7,Menages Particuliers\t,0
117563,53,Creances en souffrance / Autres / PME-PMI,2021-02-28,Bénin,BB0212V1,CBI - BENIN,7,Menages Particuliers\t,0
117564,53,Creances en souffrance / Autres / PME-PMI,2021-01-31,Bénin,BB0212V1,CBI - BENIN,7,Menages Particuliers\t,0

In [10]:
df_FISEC['Sigle Assujetti'].unique()

array(['ORABANK-BJ', 'B.O.A.', 'ECOBANK', 'BIBE', 'UBA-BENIN',
       'NSIA BANQUE BENIN', 'SGB-BÉNIN', 'BSIC-Bénin S.A.', 'BAB',
       'BGFIBANK-BENIN', 'CBAO-BENIN, SUCCURSALE', 'CCEI BANK BENIN',
       'BAIC-BENIN', 'CBI - SUCCURSALE BENIN',
       'SONIBANK-SUCCURSALE BENIN', 'CBI - BENIN'], dtype=object)